### ISSUE TITLE
Trustee Elections

### ISSUE THREAD

**Issue by meatballs** [UKPythonAssociation/ukpa-internaldocs#72]
13.1.3 of our Constitution deals with how trustee vacancies are filled at our AGM saying:

    The vacancies ... may be filled by the decision of the members at the annual general meeting

but it has nothing to say about the process we should follow to make that decision. We should create a policy to define that process.

This will become particularly necessary in the event that we have more candidates than vacancies and thus have to run a ballot,

**Comment by doismellburning** [comment]
Resolved in #80
