### ISSUE TITLE
Document label usage

### ISSUE THREAD

**Issue by doismellburning** [UKPythonAssociation/ukpa-internaldocs#82]
@meatballs I see you've added some labels here - could you document their intended usage please?

E.g. I see there are issues tagged with "Trustee Meeting Decision" ("Requires approval from a majority of trustees present at the meeting") but they don't (yet) appear to refer to any specific meeting

I *think* the intent here is that you're proposing we address this decision at a Trustee meeting (rather than one of the other methods we have of deciding things) but it's not clear - I'd love it if you could clarify please

**Comment by meatballs** [comment]
They have text associated with them which displays in hover. Are you looking for an actual doc?
